version: "3"
services:
  client:
    image: "dewaltt/multi-client"
    hostname: client
    mem_limit: 128m
  api:
    image: "dewaltt/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - BIKES_API_URL=$BIKES_API_URL
      - REQUEST_INTERVAL=$REQUEST_INTERVAL
  nginx:
    image: "dewaltt/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
